version: '3.9'
services:

  #
  # daemons
  #

  dns:
    build: dns
    restart: unless-stopped
    image: dns:latest
    volumes:
      - type: bind
        source: ./dns/conf
        target: /etc/dnsmasq.d
    ports:
      - "53:53"
      - "53:53/udp"
    dns: 192.168.15.1

  dynamicdns:
    build: dynamicdns
    restart: unless-stopped
    image: dynamicdns:latest
    secrets:
      - source: aws_credentials
        target: /root/.aws/credentials

  #
  # Web services
  #

  proxy:
    build: proxy
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./proxy/cert
        target: /etc/ssl
    image: proxy:latest
    ports:
      - "80:80"
      - "443:443"
      - "444:444"

  hello:
    build: hello
    restart: unless-stopped
    image: hello:latest

  homer:
    restart: unless-stopped
    image: b4bz/homer:latest
    volumes:
      - type: bind
        source: ./homer
        target: /www/assets
    environment:
      - UID=1000
      - GID=1000

  torrent:
    restart: unless-stopped
    image: cr.hotio.dev/hotio/qbittorrent
    ports:
      - "8080:8080"
    environment:
      - PUID=1000
      - GUID=1000
      - UMASK=002
      - TZ=America/Sao_Paulo
    volumes:
      - "./torrent:/config"
      - "${HOME}/downloads:/downloads"

secrets:
  aws_credentials:
    file: /home/andre/.aws/credentials
