version: '3.9'
services:
  dns:
    build: dns
    restart: unless-stopped
    image: dns:latest
    volumes:
      - type: bind
        source: ./dns/conf
        target: /etc/dnsmasq.d
    ports:
      - "53:53"
      - "53:53/udp"
    dns: 192.168.15.1

  dynamicdns:
    build: dynamicdns
    restart: unless-stopped
    image: dynamicdns:latest
    secrets:
      - source: aws_credentials
        target: /root/.aws/credentials

  nginx-proxy-mgr:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    environment:
      DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  hello:
    build: hello
    restart: always
    image: hello:latest
    ports:
      - "8080:80"

#  ssl_offload:
#    build: ssl_offload
#    restart: always
#    volumes:
#      - type: bind
#        source: ./ssl_offload/cert
#        target: /etc/ssl
#    image: ssl_offload:latest
#    ports:
#      - "80:80"
#      - "443:443"

#  homer:
#    restart: always
#    image: b4bz/homer:latest
#    volumes:
#      - type: bind
#        source: ./dns/conf
#        target: /www/asssets
#    ports:
#      - "8080:8080"

secrets:
  aws_credentials:
    file: /home/andre/.aws/credentials
