name: Homeserver deployment

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Homeserver
        run: |
          cat <<EOF > key.txt
          ${{secrets.SSH_PRIVATE_KEY}}
          EOF
          ssh -vvv -i key.txt -p ${{secrets.SSH_PORT}} ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "sudo -- sh -c 'cd /root/homeserver && ./start_prod.sh'"
        shell: bash
